Embed videos directly into Readme
ykdojo/kaguya pull request #23
Opened 2023-07-04 15:17 UTC by pushkaraj2007

## Changes I made:
- Moved demo videos section
- Embedded videos directly into Readme

2023-07-04 17:46 UTC, ykdojo commented
Thank you for this! I added a few comments

2023-07-04 17:47 UTC, ykdojo requested changes

2023-07-04 17:47 UTC, ykdojo commented on README.md
> +You can check out a second demo of Kaguya in action on Twitter: [Second Demo Video](https://twitter.com/ykdojo/status/1670848611532562433)
Looks like this is repetitive

2023-07-04 17:47 UTC, ykdojo commented on README.md
> +https://github.com/pushkaraj2007/kaguya/assets/107422421/6b180222-6ac5-4d42-9b40-7d48fd37f961
can we actually swap the order and show the second video first? I think it'll be more impactful that way.

also can we reduce the repetitiveness in the wording of these two sentences?

2023-07-04 19:38 UTC, pushkaraj2007 commented
Hey @ykdojo 

I have Swapped the demo videos and also removed the extra line.

I'm not sure about the repetitiveness of the words you are talking about. Can you explain it a bit more? 

Should we write it as:

Here is the first demo video of Kaguya:
and
Here is the second demo video of Kaguya:

2023-07-04 19:56 UTC, ykdojo commented
It's not that big of a deal, but it's just that those two sentences have some repetitiveness, namely: "Here's the 1st/2nd demo video of Kaguya:"

2023-07-05 12:06 UTC, pushkaraj2007 commented
@ykdojo 

What if we only keep "Here are the demo videos of Kaguya:"

And show both of the videos?

2023-07-05 12:32 UTC, ykdojo commented
That sounds good! Thank you.

On Wed, Jul 5, 2023 at 1:07 PM Pushkaraj Kulkarni ***@***.***>
wrote:

> @ykdojo <https://github.com/ykdojo>
>
> What if we only keep "Here are the demo videos of Kaguya:"
>
> And show both of the videos?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ykdojo/kaguya/pull/23#issuecomment-1621626952>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAN2JQ45NIDUUCACX5PTEEDXOVKGNANCNFSM6AAAAAAZ54BRI4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-07-05 12:33 UTC, pushkaraj2007 commented
Let me do it, real quick!

2023-07-05 12:33 UTC, pushkaraj2007 commented
Let me do it, real quick!

2023-07-05 12:52 UTC, pushkaraj2007 commented
I have made the changes. Can you please check it now?

2023-07-05 13:36 UTC, ykdojo commented
Looks good! Thank you

2023-07-05 13:37 UTC, merged